config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path("", include("warmmail.subscribe.urls", namespace="subscribe")),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("warmmail.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

warmmail/subscribe/urls.py
from django.urls import path

from warmmail.subscribe.views import (
    confirmsubscription,
    findplace,
    index,
    selectplace,
    subscribeplace,
    verifyemail,
)

app_name = "subscribe"
urlpatterns = [
    path("", index, name="index"),
    path("findplace", findplace, name="findplace"),
    path("selectplace/lat/<lat>/long/<long>", selectplace, name="select_place"),
    path(
        "subscribeplace/city/<city>/dominentpol/<dominentpol>",
        subscribeplace,
        name="subscribe_place",
    ),
    path("confirmsubscription", confirmsubscription, name="confirm_subscription"),
    path("verifyemail/<int:subscription_id>/<token>", verifyemail, name="verify_email"),
]

warmmail/users/urls.py
from django.urls import path

from warmmail.users.views import user_detail_view, user_redirect_view, user_update_view

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

warmmail/subscribe/models.py
from datetime import date

from django.db import models
from django.utils.translation import gettext_lazy as _

# Create your models here.


class Subscription(models.Model):
    """
    The main subscription model with below fields.
    Constraints: Only 1 subscription allowed per email + city combination.

    :var email: The email address of the user
    :var verified: A boolean flag indicating if the subscription has been verified
    :var temp_token: Temporary token generated for verification
    :var city: The name of the city selected
    :var dominentpol: the name of the dominent pollutant for that city
    :var next_email_date: the date when the next email has to be sent
    :var created_date: the date when this subscription was created
    :var update_date: the date when this subscription was last updated
    :var status: an ENUM if subscription is active or not
    """

    email = models.EmailField()
    verified = models.BooleanField(default=False)
    temp_token = models.CharField(max_length=24)
    city = models.CharField(max_length=100)
    dominentpol = models.CharField(max_length=100)
    next_email_date = models.DateTimeField(default=date.today())
    created_date = models.DateTimeField(default=date.today())
    update_date = models.DateTimeField(default=date.today())

    class Meta:
        unique_together = (
            "email",
            "city",
        )

    class Status(models.TextChoices):
        ACTIVE = "A", _("Active")
        INACTIVE = "I", _("Inactive")

    status = models.CharField(
        max_length=1, choices=Status.choices, default=Status.ACTIVE
    )

    def __str__(self):
        return self.email + " -> " + self.city

warmmail/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    """Default user for warmmail."""

    #: First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)
    first_name = None  # type: ignore
    last_name = None  # type: ignore

    def get_absolute_url(self):
        """Get url for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

warmmail/users/forms.py
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(admin_forms.UserCreationForm):
    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

        error_messages = {
            "username": {"unique": _("This username has already been taken.")}
        }

warmmail/subscribe/views.py
import json
import random
import string
from datetime import date, datetime, timedelta
from functools import reduce
from pathlib import Path

import environ
import pandas as pd
import plotly.express as px
import pytz
import requests

# from django.http import HttpResponse
from django.shortcuts import Http404, get_object_or_404, render
from django.template.loader import render_to_string
from plotly.offline import plot
from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail

from .models import Subscription

# Create your views here.

ROOT_DIR = Path(__file__).resolve(strict=True).parent.parent.parent
# warmmail/
APPS_DIR = ROOT_DIR / "warmmail"
env = environ.Env()

env.read_env(str(ROOT_DIR / ".env"))


def index(request):
    """
    Base view - the entry page for the website.
    Renders a page with a search box allowing the user to search for a city or location

    :param request: The HTTP request
    :return: Renders the page
    """
    return render(request, "subscribe/index.html")
    # return HttpResponse("Hello, world. You're at the polls index.")


def findplace(request):
    """
    Renders the page showing a list of all the locations. The user is allowed to submit
    a text name for the location including any significant address details (like city, country, etc.).
    Using the API exposed from geonames.org => the system renders a list of all the possible locations
    from which the user may select a location. Selecting a location means selecting a lat/long which is used
    for the subsequent steps in the journey.
    The function calls the Geonames.org API and requires an environment variable as follows:
    GEONAMES_API_USERNAME="<geonames-username>"

    :param request: HTTP request, expects a POST request with param: search_term
    :return: Renders the page
    """
    srch = request.POST["search_term"]
    response = requests.get(
        f"http://api.geonames.org/searchJSON?formatted=true&q={srch}&maxRows=10&lang=es&"
        f"username={env.str('GEONAMES_API_USERNAME')}&style=full"
    )
    if response:
        items = response.json()
        places = []
        for item in items["geonames"]:
            city = {
                "name": item["asciiName"],
                "country": item["countryCode"],
                "lat": item["lat"],
                "long": item["lng"],
            }
            places.append(city)
        return render(request, "subscribe/list_places.html", {"places": places})
    else:
        # redirect to index with error
        return render(request, "subscribe/list_places.html")


aqi_desc = {
    50: {
        "level": "Good",
        "text": "Air quality is considered satisfactory, and air pollution poses little or no risk.",
        "class": "text-success",
    },
    100: {
        "level": "Moderate",
        "text": "Air quality is acceptable; however, for some pollutants there may be a moderate health concern "
        "for a very small number of people who are unusually sensitive to air pollution.",
        "class": "text-warning",
    },
    150: {
        "level": "Unhealthy for Sensitive Groups",
        "text": "Members of sensitive groups may experience health effects. "
        "The general public is not likely to be affected.",
        "class": "text-warning",
    },
    200: {
        "level": "Unhealthy",
        "text": "Everyone may begin to experience health effects; "
        "members of sensitive groups may experience more serious health effects.",
        "class": "text-danger",
    },
    250: {
        "level": "Very Unhealthy",
        "text": "Health warnings of emergency conditions. The entire population is more likely to be affected.",
        "class": "text-danger",
    },
    300: {
        "level": "Hazardous",
        "text": "Health alert: everyone may experience more serious health effects.",
        "class": "text-danger",
    },
}


def selectplace(request, lat, long):
    """
    Renders the page showing the current AQI stats and historic graphs for the selected location.
    The page also gives a button to the user to "subscribe" to this report.
    The function calls the AQICN API and requires an environment variable as follows:
    AQICN_TOKEN="<token from aqicn>"

    :param request: HTTP GET Request
    :param lat: The selected latitute (passed automatically from findplace)
    :param long: The selected longiture (passed automatically from findplace)
    :return: Renders page with the report for the location with a button for user to subscribe.
    """
    # get the real time aqi data for this lat long
    aqi = f"https://api.waqi.info/feed/geo:{lat};{long}/?token={env.str('AQICN_TOKEN')}"
    response = requests.get(aqi, verify=False, timeout=2)
    if response:
        response = response.json()
        data = {
            "aqi": response["data"]["aqi"],
            "station": response["data"]["city"]["name"],
        }

        data["dominentpol"] = (
            response["data"]["dominentpol"]
            if response["data"]["dominentpol"]
            else "pm25"
        )

        # get aqi description
        for k, v in aqi_desc.items():
            if k > int(data["aqi"]):
                data["aqi_desc"] = v
                break

        # find the name of the city from the station name
        with open("data/airquality-covid19-cities.json", "r") as f:
            cities = json.loads(f.read())

        # readjust cities to make stations the keys
        cities = reduce(
            lambda x, y: {**x, **y},
            list(
                map(
                    lambda x: {
                        k["Name"]: {
                            "city": x["Place"]["name"],
                            "country": x["Place"]["country"],
                        }
                        for k in x["Stations"]
                    },
                    cities["data"],
                )
            ),
        )

        # our city of focus...
        city = cities[data["station"]]
        data["city"] = city["city"]

        # get parquet file
        df = pd.read_parquet(f"data/AQI_Data-{date.today()}.parquet")
        df = df[df["City"] == city["city"]].sort_index(ascending=False)
        df = df[df["Specie"].isin(["pm10", "pm25"])]
        df = df.pivot(index=None, columns="Specie", values="median")
        df.fillna(0, inplace=True)
        df.sort_index(inplace=True, ascending=False)
        last_7_days = df.iloc[:6]

        df["month"] = df.index.strftime("%Y-%m")

        df_month = df.groupby("month").agg("mean")

        last_7_days_bar = px.bar(last_7_days, title="Last 7 Days", barmode="group")
        month_bar = px.bar(df_month, title="Monthly", barmode="group")
        data["last_7_days_bar"] = plot(last_7_days_bar, output_type="div")
        data["month_bar"] = plot(month_bar, output_type="div")

        # check that the response
    return render(request, "subscribe/select_place.html", {"data": data})


def subscribeplace(request, city, dominentpol):
    """
    The last step for the subsription - this view renders a page that allows the user to subscribe to the chosen report.
    It shows a form to the user which has the following options:
    * email address - with generic verification
    * city - auto-populated basis report selected - non editable
    * time of day - gives option to user to receive report in Morning / Afternoon / Evening
    * timezone

    :param request: HTTP GET Request
    :param city: The name of the city selected for the report - auto-populated by the previous page
    :param dominentpol: The name of the dominent pollutant in that city -
        this is a hidden field in the form which is used by the backend report generation
    :return: Renders the HTML page
    """
    data = {
        "city": city,
        "dominentpol": dominentpol,
    }
    data["tz"] = pytz.all_timezones
    return render(request, "subscribe/subscribe_place.html", {"data": data})


time_of_day = {
    "M": 8,
    "A": 12,
    "E": 16,
}


def confirmsubscription(request):
    """
    A simple page which saves the subscription request and sends out an email verification link
    The email is sent via Sendgrid and requires an environment variable with the SendGrid API token:
    SENDGRID_API_KEY="<the token from Sendgrid>"

    :param request: HTTP Post request with fields from subscribeplace view
    :return: Sends out an email using SendGrid
    """
    subscription = Subscription()
    subscription.email = request.POST["email"]
    temp_token = "".join(random.choices(string.ascii_letters + string.digits, k=24))
    subscription.temp_token = temp_token
    subscription.city = request.POST["city"]
    subscription.dominentpol = request.POST["dominentpol"]

    today = datetime.now(tz=pytz.utc)
    tz = pytz.timezone(request.POST["timezone"])
    loc_time = datetime(
        today.year, today.month, today.day, time_of_day[request.POST["timeofday"]], 0, 0
    )
    loc_time = tz.localize(loc_time)
    utc_time = loc_time.astimezone(pytz.utc)
    if utc_time <= today:
        utc_time = utc_time + timedelta(days=1)

    subscription.next_email_date = utc_time

    try:
        subscription.save()
    except:  # noqa: E722
        raise Http404("Sorry! This request is invalid!")

    data = {"subscription_id": subscription.pk, "token": temp_token}
    data["host"] = request.META["HTTP_ORIGIN"]
    # send an email to verify this

    html = render_to_string("subscribe/confirm_email_template.html", {"data": data})
    message = Mail(
        from_email="sahilsakhuja85@gmail.com",
        to_emails=request.POST["email"],
        subject="Confirm your subscription from WarmMail",
        html_content=html,
    )
    try:
        sg = SendGridAPIClient(env.str("SENDGRID_API_KEY"))
        sg.send(message)
    except Exception as e:
        print(e.message)
    return render(request, "subscribe/confirm_subscription.html", {"data": data})

warmmail/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):

    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        return self.request.user.get_absolute_url()  # type: ignore [union-attr]

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

warmmail/templates/subscribe/confirm_email_template.html
{% extends "base_email.html" %}

{% block content %}

<p style="font-family: sans-serif; font-size: 14px; font-weight: normal; margin: 0; Margin-bottom: 15px;">
    <a href="{{ data.host }}/verifyemail/{{ data.subscription_id }}/{{ data.token }}">Click here</a> to verify your email address.
</p>

<p style="font-family: sans-serif; font-size: 14px; font-weight: normal; margin: 0; Margin-bottom: 15px;">
    If above link is not working, please copy and paste this link in your browsers:<br>
    {{ data.host }}/verifyemail/{{ data.subscription_id }}/{{ data.token }}
</p>

{% endblock content %}

warmmail/templates/subscribe/confirm_subscription.html
{% extends "base.html" %}

{% block content %}

Great! We've taken your request. But, there's one more step. We've have sent an email to confirm that this is a legitimate request. Please click on the link in the email to start receiving the daily updates.

{% endblock content %}

warmmail/templates/subscribe/email_confirmed.html
{% extends "base.html" %}

{% block content %}

{{ data.message }}

{% endblock content %}

warmmail/templates/subscribe/index.html
{% extends "base.html" %}

{% block content %}

    <form action="{% url 'subscribe:findplace' %}" method="post">
        {% csrf_token %}
        <div class="input-group">
            <div class="form-outline flex-fill">
                <input type="search" id="search" name="search_term" class="form-control form-control-lg" placeholder="Type in a city" />
            </div>
            <button type="submit" class="btn btn-success">
                <i class="fas fa-search"></i>
            </button>
        </div>
    </form>

{% endblock content %}

warmmail/templates/subscribe/list_places.html
{% extends "base.html" %}

{% block content %}

    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Country</th>
                <th scope="col">Lat, Long</th>
                <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody>
            {% for place in places %}
                <tr>
                    <td scope="row">{{ forloop.counter }}</td>
                    <td>{{ place.name }}</td>
                    <td>{{ place.country }}</td>
                    <td>{{ place.lat }}, {{ place.long }}</td>
                    <td><a href="{% url 'subscribe:select_place' place.lat place.long %}">Select</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

{% endblock content %}

warmmail/templates/subscribe/newsletter_email_template.html
{% extends "base_email.html" %}

{% block content %}

<p style="font-family: sans-serif; font-size: 14px; font-weight: normal; margin: 0; Margin-bottom: 15px;">
  Here's your daily update for AQI in your selected city. Keep saving energy and do your bit to save the environment!
</p>

<p style="font-family: sans-serif; font-size: 28px; font-weight: normal; margin: 0; Margin-bottom: 15px;">

  Latest AQI: {{ data.aqi }}
</p>

<table border="0" cellpadding="0" cellspacing="0" style="border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: auto;">
  <tbody>
  <tr>
    <td style="font-family: sans-serif; font-size: 28px; vertical-align: middle; text-align: center;">
      <image src="data:image/png;base64, {{ data.image_last_7_days }}"></image>
    </td>
  </tr>
  <tr>
    <td style="font-family: sans-serif; font-size: 28px; vertical-align: middle; text-align: center;">
      <image src="data:image/png;base64, {{ data.image_months }}"></image>
    </td>
  </tr>

  </tbody>

</table>

<!--                  <a href="http://htmlemail.io" target="_blank" style="display: inline-block; color: #ffffff; background-color: #3498db; border: solid 1px #3498db; border-radius: 5px; box-sizing: border-box; cursor: pointer; text-decoration: none; font-size: 14px; font-weight: bold; margin: 0; padding: 12px 25px; text-transform: capitalize; border-color: #3498db;">-->

<!--                  </a>-->

<!--- Content ends here -->

{% endblock content %}

warmmail/templates/subscribe/select_place.html
{% extends "base.html" %}

{% block content %}

<div>
    {% autoescape off %}
    <div class="row">
        <div class="col-4 offset-8" align="right">
            <a class="btn btn-primary" href="{% url 'subscribe:subscribe_place' data.city data.dominentpol %}" role="button">Subscribe</a>
        </div>
    </div>
    <div class="row align-items-center">
        <div class="col-8 order-last">
            {{ data.last_7_days_bar }}
        </div>
        <div class="col-4 order-first">
            <div class="container">
                <div class="jumbotron jumbotron-fluid">
                  <div class="container">
                      <h1 class="display-1 {{ data.aqi_desc.class }}">{{ data.aqi }}</h1>
                      <div class="lead" style="margin-left: 15px">
                        <h4 class="{{ data.aqi_desc.class }}">{{ data.aqi_desc.level }}</h4><br>
                      {{ data.aqi_desc.text }}
                      </div>
                  </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row align-items-center">
        <div class="col-12">
            {{ data.month_bar }}
        </div>
<!--        <div class="col">-->

<!--            <img src="data:image/png;base64,{{ data.image }}" />-->

<!--        </div>-->

    </div>
    {% endautoescape %}
</div>



{% endblock content %}

warmmail/templates/subscribe/subscribe_place.html
{% extends "base.html" %}

{% block content %}

{{ data.env }}

<div>
    <div class="container">
        <form action="{% url 'subscribe:confirm_subscription' %}" method="post">
            {% csrf_token %}
            <div class="form-row">
                <div class="col">
                    <div class="form-group">
                        <label for="email">Email address</label>
                        <input type="email" class="form-control" id="email" name="email" aria-describedby="emailHelp" placeholder="Enter email address" required>
                        <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
                    </div>
                </div>
                <div class="col">
                    <div class="form-group">
                        <label for="station">AQI City Name</label>
                        <input type="text" readonly class="form-control" id="city" name="city" aria-describedby="cityName" value="{{ data.city }}">
                        <input type="hidden" name="dominentpol" value="{{ data.dominentpol }}" />
                        <small id="stationName" class="form-text text-muted">We'll send you updates from this city - that's where your closest station is located.</small>
                    </div>
                </div>
            </div>
            <div class="form-row">
                <div class="col">
                    <p>Time of day:</p>
                    <div class="form-check form-check-inline">
                        <input class="form-check-input" type="radio" name="timeofday" id="morning" value="M" checked="true">
                        <label class="form-check-label" for="morning">Morning</label>
                    </div>
                    <div class="form-check form-check-inline">
                        <input class="form-check-input" type="radio" name="timeofday" id="afternoon" value="A">
                        <label class="form-check-label" for="afternoon">Afternoon</label>
                    </div>
                    <div class="form-check form-check-inline">
                        <input class="form-check-input" type="radio" name="timeofday" id="evening" value="E">
                        <label class="form-check-label" for="evening">Evening</label>
                    </div>
                </div>
                <div class="col">
                    <p>Timezone:</p>
                    <select class="form-control form-control-sm" name="timezone">
                        {% for tz in data.tz %}
                        <option value="{{ tz }}">{{ tz }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
            <div class="form-row mt-5">
                <div class="col offset-11">
                    <button type="submit" class="btn btn-primary">Subscribe</button>
                </div>
            </div>
        </form>
    </div>
</div>

{% endblock content %}